### ISSUE TITLE
Oyeeeee

### ISSUE THREAD

**Issue by aayushdewangan11** [ananyatiwari2709/Food-Service-Database#1]
Question 10 firse explain karna 🦭

**Comment by ananyatiwari2709** [comment]
Suppose a customer becomes a gold member on x date. Now after that, from that date to next 1 year, if he purchases any item whether p1, p2 or p3 he gets 5 points for spending 10 Rs. And we have to find total points of customers during this 1 year period. Since we know from previous queries that user 1 and 3 are only gold members, so question is asking to compare their points.

**Comment by aayushdewangan11** [comment]
Samjh gaya🫡
Kaha hai aaj kal? gayab hi ho gai hai ekdam
